In [14]:
import pathlib
import pandas as pd

In [16]:
liar_data = pd.read_csv("data/liar_dataset/train.tsv",sep='\t')
liar_data.head()

,2635.json,false,Says the Annies List political group supports third-trimester abortions on demand.,abortion,dwayne-bohac,State representative,Texas,republican,0,1,0.1,0.2,0.3,a mailer
0,10540.json,half-true,When did the decline of coal start? It started...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.
1,324.json,mostly-true,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver
2,1123.json,false,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release
3,9028.json,half-true,The economic turnaround started at the end of ...,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN
4,12465.json,true,The Chicago Bears have had more starting quart...,education,robin-vos,Wisconsin Assembly speaker,Wisconsin,republican,0.0,3.0,2.0,5.0,1.0,a an online opinion-piece

In [24]:
hugging_face_data = pd.read_excel('data/hugging_face/Fake_News_Stories.xlsx')
hugging_face_data.head()

,Article Number,URL of article,Fake or Satire?,URL of rebutting article,Fake or Satire?.1
0,375,http://www.redflagnews.com/headlines-2016/cdc-...,Fake,http://www.snopes.com/cdc-forced-vaccinations/,Fake
1,376,http://www.redflagnews.com/headlines-2016/-out...,Fake,http://www.snopes.com/white-house-logo-change/,Fake
2,377,http://www.redflagnews.com/headlines-2016/whit...,Fake,http://www.snopes.com/obama-veterans-money-to-...,Fake
3,378,http://www.redflagnews.com/headlines-2016/obam...,Fake,http://www.snopes.com/obama-veterans-money-to-...,Fake
4,379,http://www.redflagnews.com/headlines-2016/cali...,Fake,http://www.snopes.com/california-to-jail-clima...,Fake

In [25]:
fn_data = pd.read_csv('data/fake-news/train.csv')
fn_data.head()

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1